// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID   *int   `json:"id"`
	Name string `json:"name"`
}

type Image struct {
	Title   string  `json:"title"`
	Comment *string `json:"comment"`
	Scr     *string `json:"scr"`
}

type Product struct {
	ID          *int        `json:"id"`
	Name        string      `json:"name"`
	Price       *float64    `json:"price"`
	Description *string     `json:"description"`
	Size        *string     `json:"size"`
	Category    []*Category `json:"category"`
}
