// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ImageContract struct {
	Title   string  `json:"title"`
	Comment *string `json:"comment"`
	Scr     *string `json:"scr"`
}
